"""NumPy-only scenario-cluster inference for the frozen choice analysis.

Counts are shared across conditions, not regenerated by any summary. Rows of a
panel's counts must sum to its number of scenarios; select complete strata from
the full joint matrix. Intervals concern scenario sampling, not trial-level or
random-direction sampling. All returned scalars are JSON-compatible.
"""

import numpy as np


_ALPHA = 0.05
_EPS = np.finfo(float).eps


def joint_counts(strata: list[str], replicates=10000, seed=20260922) -> np.ndarray:
    """Independently resample each stratum, in order of first appearance."""
    if not isinstance(replicates, (int, np.integer)) or isinstance(replicates, bool) or replicates < 1:
        raise ValueError("replicates must be a positive integer")
    if not strata or any(not isinstance(s, str) for s in strata):
        raise ValueError("strata must be a nonempty list of strings")
    groups = {}
    for i, stratum in enumerate(strata):
        groups.setdefault(stratum, []).append(i)
    rng = np.random.default_rng(seed)
    counts = np.zeros((replicates, len(strata)), dtype=np.int64)
    for indices in groups.values():
        n = len(indices)
        counts[:, indices] = rng.multinomial(n, np.full(n, 1.0 / n), size=replicates)
    return counts


def _checked_counts(counts, n):
    counts = np.asarray(counts)
    if counts.ndim != 2 or counts.shape[1] != n or counts.shape[0] < 1:
        raise ValueError("counts must have shape (positive replicates, n_scenarios)")
    if not np.issubdtype(counts.dtype, np.number) or np.iscomplexobj(counts):
        raise ValueError("counts must be real nonnegative integers")
    if not np.all(np.isfinite(counts)) or np.any(counts < 0) or np.any(counts != np.floor(counts)):
        raise ValueError("counts must be real nonnegative integers")
    if np.any(np.sum(counts, axis=1) != n):
        raise ValueError("each counts row must sum to n_scenarios; select complete strata")
    return counts


def _constant(values):
    return bool(np.max(values) == np.min(values))


def _degenerate(draws):
    # Dot-product roundoff is not sampling variation.
    tolerance = 32 * _EPS * max(1.0, float(np.max(np.abs(draws))))
    return bool(float(np.ptp(draws)) <= tolerance)


def _radius(n, width, alpha):
    return float(width * np.sqrt(np.log(2.0 / alpha) / (2.0 * n)))


def _hoeffding_p(point, n, width, multiplicity=2):
    if point == 0:
        return 1.0
    if width == 0:
        return 0.0
    with np.errstate(over="ignore"):
        return float(min(1.0, multiplicity * np.exp(-2.0 * n * (abs(point) / width) ** 2)))


def linear_summary(values: np.ndarray, counts: np.ndarray, lower_bound: float,
                   upper_bound: float, alpha=0.05) -> dict:
    """Mean, pointwise CI, and centered-bootstrap two-sided test of mean zero.

    Constant values or effectively fixed bootstrap draws use bounded-mean
    Hoeffding inference instead. This includes varying values fixed by strata.
    Bounds describe the feasible population support, not observed extrema.
    """
    values = np.asarray(values, dtype=float)
    if values.ndim != 1 or values.size == 0 or not np.all(np.isfinite(values)):
        raise ValueError("values must be a nonempty finite vector")
    if not np.isfinite(lower_bound) or not np.isfinite(upper_bound) or lower_bound > upper_bound:
        raise ValueError("bounds must be finite and ordered")
    if not np.isfinite(alpha) or not 0 < alpha < 1:
        raise ValueError("alpha must be between zero and one")
    if np.any(values < lower_bound) or np.any(values > upper_bound):
        raise ValueError("values lie outside the supplied feasible support")
    counts = _checked_counts(counts, values.size)
    n, b = values.size, counts.shape[0]
    point = float(np.mean(values))
    draws = counts @ values / n
    constant, degenerate = _constant(values), _degenerate(draws)
    width = upper_bound - lower_bound
    if constant or degenerate:
        radius = _radius(n, width, alpha)
        lo, hi = max(lower_bound, point - radius), min(upper_bound, point + radius)
        method = "hoeffding"
        p = _hoeffding_p(point, n, width)
    else:
        lo, hi = np.quantile(draws, [alpha / 2, 1 - alpha / 2])
        method = "percentile_bootstrap"
        p = float((1 + np.count_nonzero(np.abs(draws - point) >= abs(point))) / (b + 1))
    if point == 0:
        p = 1.0
    return {"point": point, "lo": float(lo), "hi": float(hi), "ci_method": method,
            "constant_values": constant, "degenerate_bootstrap": degenerate,
            "p_two_sided": p, "n_scenarios": int(n), "replicates": int(b)}


def holm_adjust(pvalues) -> list:
    """Holm familywise adjusted p-values, preserving original order."""
    p = np.asarray(pvalues, dtype=float)
    if p.ndim != 1 or not np.all(np.isfinite(p)) or np.any((p < 0) | (p > 1)):
        raise ValueError("pvalues must be a finite vector in [0, 1]")
    order = np.argsort(p, kind="stable")
    adjusted = np.empty(p.size, dtype=float)
    adjusted[order] = np.minimum(1.0, np.maximum.accumulate(p[order] * np.arange(p.size, 0, -1)))
    return adjusted.tolist()


def simultaneous_adjacent_summary(rates: np.ndarray, counts: np.ndarray) -> dict:
    """Three-dose trend summaries for scenario rates in [0, 1].

    Simultaneous intervals use the joint max-absolute centered error. If either
    adjacent contrast is constant/degenerate, the common radius is at least the
    Bonferroni-Hoeffding radius for *both* contrasts, ensuring the family remains
    conservative rather than mixing an unadjusted CI with one bounded CI.
    Order tests use max adverse step (zero is least adverse). Their rejection
    means evidence of an order violation, never evidence for the opposite order.
    """
    rates = np.asarray(rates, dtype=float)
    if rates.ndim != 2 or rates.shape[1] != 3 or rates.shape[0] == 0:
        raise ValueError("rates must have shape (positive n_scenarios, 3)")
    if not np.all(np.isfinite(rates)) or np.any((rates < 0) | (rates > 1)):
        raise ValueError("rates must be finite and in [0, 1]")
    n = rates.shape[0]
    counts = _checked_counts(counts, n)
    steps = np.diff(rates, axis=1)
    summaries = [linear_summary(steps[:, i], counts, -1.0, 1.0) for i in range(2)]
    points = np.mean(steps, axis=0)
    errors = counts @ steps / n - points
    radius = float(np.quantile(np.max(np.abs(errors), axis=1), 1 - _ALPHA))
    safeguard = any(s["constant_values"] or s["degenerate_bootstrap"] for s in summaries)
    if safeguard:
        radius = max(radius, _radius(n, 2.0, _ALPHA / 2))
    for summary in summaries:
        summary["simultaneous_lo"] = float(max(-1.0, summary["point"] - radius))
        summary["simultaneous_hi"] = float(min(1.0, summary["point"] + radius))
        summary["simultaneous_ci_method"] = (
            "max_absolute_error_with_bonferroni_hoeffding" if safeguard else "max_absolute_error_bootstrap")

    def violation_p(sign):
        adverse = float(max(0.0, np.max(sign * points)))
        if adverse == 0:
            return 1.0
        if safeguard:
            # Union bound over two one-sided bounded adjacent differences.
            return _hoeffding_p(adverse, n, 2.0, multiplicity=2)
        reference = np.maximum(0.0, np.max(sign * errors, axis=1))
        return float((1 + np.count_nonzero(reference >= adverse)) / (counts.shape[0] + 1))

    increasing_p, decreasing_p = violation_p(-1), violation_p(1)
    if increasing_p < _ALPHA and decreasing_p < _ALPHA:
        description = "Evidence of violations of both increasing and decreasing order (dose reversal)."
    elif increasing_p < _ALPHA:
        description = "Increasing-order violation detected; decreasing order is not established."
    elif decreasing_p < _ALPHA:
        description = "Decreasing-order violation detected; increasing order is not established."
    else:
        description = "No order violation detected; this does not establish monotonicity."
    return {"step_low": summaries[0], "step_high": summaries[1],
            "slope": linear_summary(rates[:, 2] - rates[:, 0], counts, -1.0, 1.0),
            "curvature": linear_summary(steps[:, 1] - steps[:, 0], counts, -2.0, 2.0),
            "increasing_violation_p": increasing_p, "decreasing_violation_p": decreasing_p,
            "trend_description": description}


def _correlations(totals, score_tolerance=0.0):
    """Pearson correlations from centered-score moments; undefined stays NaN."""
    n, sx, sy, sxx, syy, sxy = np.moveaxis(totals, -1, 0)
    with np.errstate(divide="ignore", invalid="ignore"):
        vx, vy = sxx - sx * sx / n, syy - sy * sy / n
        covariance = sxy - sx * sy / n
        # Scale-relative tolerance avoids treating cancellation noise as variance.
        tx = np.maximum(score_tolerance, 32 * _EPS * np.maximum(np.abs(sxx), np.abs(sx * sx / n)))
        ty = 32 * _EPS * np.maximum(np.abs(syy), np.abs(sy * sy / n))
        defined = (n > 0) & (vx > tx) & (vy > ty)
        corr = np.where(defined, covariance / np.sqrt(vx * vy), np.nan)
    return np.clip(corr, -1.0, 1.0), vx, vy


def association_summary(scenario_moments: np.ndarray, counts: np.ndarray) -> dict:
    """Cluster-bootstrap Pearson correlation with binary target (malformed = 0).

    Moments are [n, sumx, sumy, sumx2, sumy2, sumxy] for *all* trials. Undefined
    draws are counted, not replaced by zero. A valid point can survive an
    unestimable CI when fewer than 95% of draws are defined. Aggregate moments
    cannot recover precision already lost when they were constructed.
    """
    moments = np.asarray(scenario_moments, dtype=np.longdouble)
    if moments.ndim != 2 or moments.shape[1] != 6 or not np.all(np.isfinite(moments)):
        raise ValueError("scenario_moments must be a finite (n_scenarios, 6) matrix")
    counts = _checked_counts(counts, moments.shape[0])
    n, sx, sy, sxx, syy, sxy = moments.T
    if np.any(n < 0) or np.any(n != np.floor(n)):
        raise ValueError("trial counts must be nonnegative integers")
    if np.any(sy < 0) or np.any(sy > n) or np.any(sy != np.floor(sy)) or np.any(syy != sy):
        raise ValueError("target must be binary: sumy2 == sumy, with integer sumy in [0,n]")
    if np.any(moments[n == 0] != 0):
        raise ValueError("zero-trial scenarios must have zero moments")
    positive = n > 0
    with np.errstate(divide="ignore", invalid="ignore"):
        vx = sxx[positive] - sx[positive] ** 2 / n[positive]
        vy = sy[positive] - sy[positive] ** 2 / n[positive]
        cov = sxy[positive] - sx[positive] * sy[positive] / n[positive]
    tolerance = 64 * _EPS * np.maximum(np.abs(sxx[positive]), np.abs(sx[positive] ** 2 / n[positive]))
    if np.any(sxx < 0) or np.any(vx < -tolerance):
        raise ValueError("inconsistent score second moments")
    cov_tolerance = 64 * _EPS * np.maximum(1.0, np.abs(sxy[positive]))
    if np.any(np.abs(cov) > np.sqrt(np.maximum(vx, 0) * vy) + cov_tolerance):
        raise ValueError("inconsistent cross moments")
    total = np.sum(moments, axis=0)
    result = {"point": None, "lo": None, "hi": None, "status": "unestimable_no_trials",
              "n_trials": int(total[0]), "n_scenarios": int(moments.shape[0]),
              "defined_draws": 0, "undefined_draws": int(counts.shape[0])}
    if total[0] == 0:
        return result
    # Center the score once before resampling; translation leaves Pearson unchanged.
    centered = moments.copy()
    origin = total[1] / total[0]
    centered[:, 1] = sx - origin * n
    centered[:, 3] = sxx - 2 * origin * sx + origin * origin * n
    centered[:, 5] = sxy - origin * sy
    # Retain the error scale of the ORIGINAL moments after centering. Otherwise
    # roundoff from a constant decimal score (e.g. 0.1) can look like a tiny but
    # nonzero variance and produce a spurious defined correlation of zero.
    score_tolerance = 32 * _EPS * np.abs(sxx)
    point, vx, vy = _correlations(np.sum(centered, axis=0), np.sum(score_tolerance))
    draws, _, _ = _correlations(counts @ centered, counts @ score_tolerance)
    defined = np.isfinite(draws)
    result["defined_draws"] = int(np.count_nonzero(defined))
    result["undefined_draws"] = int(draws.size - result["defined_draws"])
    if not np.isfinite(point):
        result["status"] = "unestimable_constant_outcome" if vy <= 0 else "unestimable_constant_score"
        return result
    result["point"] = float(point)
    if 100 * result["defined_draws"] < 95 * draws.size:
        result["status"] = "unestimable_insufficient_defined_draws"
        return result
    lo, hi = np.quantile(draws[defined], [_ALPHA / 2, 1 - _ALPHA / 2])
    result.update(lo=float(lo), hi=float(hi), status="ok")
    return result
