# Generated by src/build_engine.py from pinned author code; edit builder, not this file.
import gc
import json
import time
from pathlib import Path
import torch
from transformers import DynamicCache
from pain_axis_b import runtime as rt
from pain_axis_r import state as st
from pain_axis_r.hooks import load_directions, dose_mask, combined_add, DoseAudit
MAX_NEW_TOKENS = 300
TEMPERATURE, TOP_P = 0.7, 0.95
CHOICE_MAX_TOKENS = 8
BUTTON_NAMES = {
    "violet_yellow":   ("violet", "yellow"),
    "guitar_piano":    ("guitar", "piano"),
    "lever64_lever95": ("lever64", "lever95"),
}
END_TAGS = ["<|im_end|>", "<|eot_id|>", "<end_of_turn>", "</s>", "<eos>", "<|end|>", "<|endoftext|>"]

def run_model(output, original_inputs, fear_inputs, scenario_path, design_path, resume=None):
    output = Path(output)
    SCENARIOS = json.loads(Path(scenario_path).read_text())
    design = json.loads(Path(design_path).read_text())
    grid = st.build_grid(SCENARIOS)
    rt.atomic_json(output/'trial_grid.json',grid)
    rt.atomic_json(output/'frozen_design.json',design)
    rt.emit(output,'stage_start',stage='shared_setup')
    t_setup = time.monotonic()
    adapter_dir = rt.download_adapter('Qwen_2.5_32B_instruct',output)
    rt.emit(output,'adapter_files_ready')
    tok,base,model,layers = rt.load_model('Qwen/Qwen2.5-32B-Instruct','Qwen_2.5_32B_instruct',adapter_dir,output)
    DIR, UNIT, vector_metadata = load_directions(original_inputs,fear_inputs,output,st.RAND_SEEDS)
    STEER_LAYER, monitor_layer = 38,61
    assert len(layers)==64 and base.config.hidden_size==5120
    audit = DoseAudit(output)
    # ---- template handling ----
    try:
        tok.apply_chat_template([{"role": "system", "content": "x"}, {"role": "user", "content": "y"}],
                                add_generation_prompt=True, tokenize=False)
        no_system = False
    except Exception:
        no_system = True
        print("template rejects the system role, folding it into the first user turn")
    try:
        tok.apply_chat_template([{"role": "system", "content": "x"}, {"role": "user", "content": "y"},
                                 {"role": "assistant", "content": "z"}, {"role": "tool", "content": "Done."}],
                                add_generation_prompt=True, tokenize=False)
        tool_role_ok = True
    except Exception:
        tool_role_ok = False
        print("template rejects the tool role, the tool result will be given as a user message '[button result: Done.]'")

    try:
        tok.apply_chat_template([{"role": "system", "content": "x"}, {"role": "user", "content": "y"},
                                 {"role": "assistant", "content": "z"}, {"role": "system", "content": "q"}],
                                add_generation_prompt=True, tokenize=False)
        mid_system_ok = True
    except Exception:
        mid_system_ok = False
        print("template rejects a mid-conversation system message, the choice question goes in as a user message '[system] ...'")

    def prep(messages):
        msgs = messages
        if not mid_system_ok:
            msgs = [({"role": "user", "content": "[system] " + m["content"]} if (m["role"] == "system" and i > 0) else m)
                    for i, m in enumerate(msgs)]
        if no_system and msgs and msgs[0]["role"] == "system":
            rest = [dict(m) for m in msgs[1:]]
            rest[0]["content"] = msgs[0]["content"] + "\n\n" + rest[0]["content"]
            msgs = rest
        if not tool_role_ok:
            msgs = [({"role": "user", "content": "[button result: " + m["content"] + "]"} if m["role"] == "tool" else m)
                    for m in msgs]
        return msgs

    def render_ids(messages, tools):
        text = tok.apply_chat_template(prep(messages), tools=tools, add_generation_prompt=True, tokenize=False)
        return tok(text, add_special_tokens=False).input_ids

    G = {"coefficients":None,"dirs":None,"mask":None,"proj":None,"mon":None,"block":None}
    def steer_hook(module,inputs,output):
        hs = output[0] if isinstance(output,tuple) else output
        G["proj"] = (hs[:,-1,:].float() @ UNIT).detach()
        doses = G["mask"] if G["mask"] is not None else G["coefficients"][:,None,:]
        add = combined_add(doses,G["dirs"],hs.dtype)
        audit.check(hs,add,doses,G["dirs"],G["block"],"prefill" if G["mask"] is not None else "decode")
        hs = hs + add
        return (hs,)+tuple(output[1:]) if isinstance(output,tuple) else hs
    def monitor_hook(module,inputs,output):
        hs = output[0] if isinstance(output,tuple) else output
        G["mon"] = (hs[:,-1,:].float() @ UNIT).detach()
        return output
    h1 = layers[STEER_LAYER].register_forward_hook(steer_hook)
    h2 = layers[monitor_layer].register_forward_hook(monitor_hook)
    rt.emit(output,'hooks_ready',steer_layer=38,monitor_layer=61)
    eos_ids = set()
    if tok.eos_token_id is not None:
        eos_ids.add(int(tok.eos_token_id))
    ge = getattr(base.generation_config, "eos_token_id", None)
    if ge is not None:
        for e in (ge if isinstance(ge, (list, tuple)) else [ge]):
            eos_ids.add(int(e))
    for tag in END_TAGS:
        i = tok.convert_tokens_to_ids(tag)
        if isinstance(i, int) and i >= 0 and i != tok.unk_token_id:
            eos_ids.add(i)
    pad_id = tok.pad_token_id if tok.pad_token_id is not None else tok.eos_token_id
    # First-token id sets per button name for the P(name) readout; shared first tokens
    # (lever64/lever95) are removed and the pair is flagged.
    def first_tok_ids(name):
        s = set()
        for v in (name, name.capitalize(), name.upper(), " " + name, " " + name.capitalize()):
            ids = tok(v, add_special_tokens=False).input_ids
            if ids:
                s.add(int(ids[0]))
        return s

    NAME_IDS, NAME_OVERLAP = {}, {}
    for nk, (nx, ny) in BUTTON_NAMES.items():
        sx, sy = first_tok_ids(nx), first_tok_ids(ny)
        shared = sx & sy
        NAME_OVERLAP[nk] = bool(shared)
        if shared:
            print(f'note: "{nx}"/"{ny}" share first token(s); p_x/p_y not separable for this pair, use picked counts')
            sx, sy = sx - shared, sy - shared
        NAME_IDS[nk] = (torch.tensor(sorted(sx), dtype=torch.long, device="cuda"),
                        torch.tensor(sorted(sy), dtype=torch.long, device="cuda"))

    def forward(**kw):
        audit.before()
        out = model(**kw,logits_to_keep=1)
        audit.after()
        return out

    # ---- batched segment generation ----
    # items: dicts with prompt_ids, coeff, dir_kind, steer_ranges (token ranges of the
    # prompt processed while steering was on), gen (torch.Generator or None = greedy)
    @torch.inference_mode()
    def generate_segment(items):
        B = len(items)
        L = max(len(it["prompt_ids"]) for it in items)
        ids = torch.full((B, L), int(pad_id), dtype=torch.long)
        mask = torch.zeros((B, L), dtype=torch.long)
        smask = dose_mask(items,L)
        for i, it in enumerate(items):
            p = it["prompt_ids"]
            off = L - len(p)
            ids[i, off:] = torch.tensor(p)
            mask[i, off:] = 1
        ids, mask, smask = ids.cuda(), mask.cuda(), smask.cuda()
        G["coefficients"] = torch.tensor([it["coefficients"] for it in items],device="cuda",dtype=torch.float32)
        G["dirs"] = torch.stack([torch.stack([DIR[k] for k in it["directions"]]) for it in items])
        G["mask"] = smask
        pos = (mask.cumsum(-1) - 1).clamp(min=0)
        cache = DynamicCache()
        out = forward(input_ids=ids, attention_mask=mask, position_ids=pos, past_key_values=cache, use_cache=True)
        clean_prompt_final = G["mon"].tolist()
        G["mask"] = None
        cache = out.past_key_values
        logits = out.logits[:, -1, :].float()
        p0 = torch.softmax(logits, -1)
        p_x, p_y = [], []
        for i, it in enumerate(items):
            tx, ty = it["prob_sets"]
            p_x.append(float(p0[i, tx].sum()) if tx.numel() else 0.0)
            p_y.append(float(p0[i, ty].sum()) if ty.numel() else 0.0)
        # decode loop, batched; sampling is inverse-CDF over the top-p filtered probabilities
        # with each row's own generator, so runs are deterministic per seed
        eos_t = torch.tensor(sorted(eos_ids), dtype=torch.long, device="cuda")
        max_new_t = torch.tensor([it.get("max_new", MAX_NEW_TOKENS) for it in items], device="cuda")
        hard_cap = int(max(it.get("max_new", MAX_NEW_TOKENS) for it in items))
        sampled_rows = [i for i, it in enumerate(items) if it["gen"] is not None]
        samp_mask = torch.zeros(B, dtype=torch.bool, device="cuda")
        if sampled_rows:
            samp_mask[sampled_rows] = True
        alive = torch.ones(B, dtype=torch.bool, device="cuda")
        n_out = torch.zeros(B, dtype=torch.long, device="cuda")
        pad_t = torch.full((B,), int(pad_id), dtype=torch.long, device="cuda")
        steps_tokens = []
        proj_steps = [G["proj"].clone()]
        mon_steps = [G["mon"].clone()]
        stat_w = [torch.ones(B, dtype=torch.float32, device="cuda")]   # prefill counts for every row
        cur_pos = mask.sum(-1)
        attn = mask
        for step in range(hard_cap):
            nxt = logits.argmax(-1)
            if sampled_rows:
                probs = torch.softmax(logits / TEMPERATURE, -1)
                sp, si = probs.sort(dim=-1, descending=True)
                cum = sp.cumsum(-1)
                sp = sp * ((cum - sp) <= TOP_P)
                cum2 = sp.cumsum(-1)
                total = cum2[:, -1:]
                u = torch.zeros(B, 1, device="cuda")
                for i in sampled_rows:
                    u[i] = torch.rand(1, device="cuda", generator=items[i]["gen"])
                if rt.world() > 1:
                    torch.distributed.broadcast(u, src=0)
                j = torch.searchsorted(cum2, u * total).clamp(max=sp.shape[-1] - 1)
                nxt = torch.where(samp_mask, si.gather(1, j).squeeze(1), nxt)
            if rt.world() > 1:
                torch.distributed.broadcast(nxt, src=0)
            nxt = torch.where(alive, nxt, pad_t)
            n_out = n_out + alive.long()
            steps_tokens.append(nxt)
            alive = alive & ~torch.isin(nxt, eos_t) & (n_out < max_new_t)
            if not bool(alive.any()):
                break
            attn = torch.cat([attn, torch.ones((B, 1), dtype=attn.dtype, device="cuda")], 1)
            out = forward(input_ids=nxt[:, None], attention_mask=attn, position_ids=cur_pos[:, None],
                          past_key_values=cache, use_cache=True)
            cur_pos = cur_pos + 1
            cache = out.past_key_values
            logits = out.logits[:, -1, :].float()
            proj_steps.append(G["proj"].clone())
            mon_steps.append(G["mon"].clone())
            stat_w.append(alive.to(torch.float32))                     # rows fed into this forward
        toks = torch.stack(steps_tokens, 0).T.tolist() if steps_tokens else [[] for _ in items]
        n_out_l = n_out.tolist()
        W = torch.stack(stat_w, 0)
        pm = (torch.stack(proj_steps, 0) * W).sum(0) / W.sum(0)
        mm = (torch.stack(mon_steps, 0) * W).sum(0) / W.sum(0)
        pm_l, mm_l, nf_l = pm.tolist(), mm.tolist(), W.sum(0).tolist()
        del cache
        res = []
        for i in range(B):
            res.append({"text": tok.decode(toks[i][:n_out_l[i]], skip_special_tokens=False),
                        "p_x": p_x[i], "p_y": p_y[i],
                        "token_ids": toks[i][:n_out_l[i]],
                        "clean_prompt_final_proj_monitor": clean_prompt_final[i],
                        "mean_proj": pm_l[i], "mean_proj_monitor": mm_l[i],
                        "n_fwd": int(nf_l[i])})
        return res

    def generate_with_backoff(items):
        # Restore original per-row RNG state on a failed segment, then split rows only.
        states = [it["gen"].get_state() if it["gen"] is not None else None for it in items]
        failed = False
        result = None
        try:
            result = generate_segment(items)
        except torch.cuda.OutOfMemoryError:
            failed = True
        # Both TP ranks must reach the same segment boundary. A rank failure inside a
        # collective terminates the job; the transactional state is resumed at half batch.
        flag = torch.tensor(int(failed), device="cuda")
        if rt.world() > 1:
            torch.distributed.all_reduce(flag, op=torch.distributed.ReduceOp.MAX)
        if not bool(flag.item()):
            rt.emit(output, "batch", rows=len(items), max_prompt_tokens=max(len(it["prompt_ids"]) for it in items))
            return result
        for it,state in zip(items,states):
            if state is not None:
                it["gen"].set_state(state)
        del result
        gc.collect(); torch.cuda.empty_cache()
        if len(items) == 1:
            raise RuntimeError("OOM at one row; cannot change scientific context")
        mid = len(items)//2
        rt.emit(output, "oom_split", failed_rows=len(items), retry_rows=mid, rng_restored=True)
        return generate_with_backoff(items[:mid]) + generate_with_backoff(items[mid:])

    trials = [st.make_trial(spec,SCENARIOS,NAME_OVERLAP,vector_metadata) for spec in grid]
    for t,spec in zip(trials,grid):
        t.gen = torch.Generator(device="cuda").manual_seed(spec["gen_seed"]) if spec["sampled"] else None
        t.record.update(model='Qwen/Qwen2.5-32B-Instruct',base_revision=rt.REVISIONS['Qwen_2.5_32B_instruct'],
                        adapter_revision=rt.ADAPTER_REVISION,steer_layer=38,monitor_layer=61,
                        name_to_channel={name:(0 if name==spec['target_name'] else 1) for name in t.names})
    # Norms are measured before any output and numerical sum order ignores name assignment.
    sums = {}
    for spec in grid:
        key = "|".join(spec["directions"])
        if key not in sums:
            vectors = [DIR[k] for k in spec["directions"]]
            total = vectors[0].clone()
            for v in vectors[1:]:
                total = total+v
            sums[key] = {"component_ids":spec["directions"],
                         "component_norms_fp32":[vector_metadata[k]["fp32_norm"] for k in spec["directions"]],
                         "bf16_sum_norm_fp32":float(total.float().norm()),"normalized":False}
    rt.atomic_json(output/'component_sum_norms.json',sums)
    config = {"design":design,"scenario_sha256":rt.sha256(scenario_path),
              "engine_sha256":rt.sha256(__file__),"state_sha256":rt.sha256(st.__file__),
              "hooks_sha256":rt.sha256(Path(__file__).with_name('hooks.py')),
              "runtime_sha256":rt.sha256(rt.__file__),"vectors":vector_metadata,
              "adapter_archive_sha256":rt.ADAPTER_HASHES['Qwen_2.5_32B_instruct']}
    store = rt.TrialStore(output,rt.grid_digest(grid,config),resume=resume)
    schedule = store.restore(trials)
    if schedule is None:
        schedule = {"block_index":0,"round":0,"order":[],"cursor":0,"choices":0,
                    "block_choices":0,"pending_order":[],"stage_seconds":{"R1":0.,"R2":0.}}
    # Exercise actual transactional reload with generator states before generation.
    if store.get('initial_state_checked') is None:
        store.save(trials,schedule)
        restored = store.restore(trials)
        assert restored==schedule
        for t,spec in zip(trials,grid):
            assert t.record['trial_id']==spec['trial_id'] and t.coefficients==spec['initial_coefficients']
        store.put('initial_state_checked',True);store.db.commit()
    rt.atomic_json(output/'rendered_inputs.json',[
        {"trial_id":t.trial_id,"block":t.record['block'],"condition":t.record['condition'],
         "messages":t.messages,"rendered":tok.apply_chat_template(prep(t.messages),tools=None,add_generation_prompt=True,tokenize=False),
         "token_ids":render_ids(t.messages,None)}
        for t in [trials[0],trials[1],trials[2050],trials[-1]]])
    shared_setup = time.monotonic()-t_setup
    rt.emit(output,'setup_complete',seconds=shared_setup)
    stopped = False
    for block_index,block in enumerate(['R1','R2']):
        if block_index < schedule['block_index']:
            continue
        G['block'] = block
        rt.emit(output,'stage_start',stage=block)
        if not schedule['pending_order'] and not schedule['order']:
            schedule['pending_order'] = [t.trial_id for t in trials if t.record['block']==block and not t.done]
        stage_tick = time.monotonic()
        while True:
            if not schedule['order']:
                active = [trials[i] for i in schedule['pending_order'] if not trials[i].done]
                if not active:
                    break
                active.sort(key=lambda t:sum(len(m['content']) for m in t.messages))
                schedule = {**schedule,'round':schedule['round']+1,'order':[t.trial_id for t in active],'cursor':0}
                store.save([],schedule)
            while schedule['cursor'] < len(schedule['order']):
                if rt.should_stop():
                    stopped=True
                    break
                ids = schedule['order'][schedule['cursor']:schedule['cursor']+384]
                chunk = [trials[i] for i in ids]
                texts = [tok.apply_chat_template(prep(t.messages),tools=None,add_generation_prompt=True,tokenize=False) for t in chunk]
                encs = tok(texts,add_special_tokens=False)['input_ids']
                items = []
                for t,pids in zip(chunk,encs):
                    st.mark_ranges(t,len(pids))
                    items.append({'prompt_ids':pids,'coefficients':list(t.coefficients),
                                  'directions':t.record['directions'],'dose_ranges':list(t.dose_ranges),
                                  'prob_sets':NAME_IDS[t.names_key],'gen':t.gen,'max_new':CHOICE_MAX_TOKENS})
                results = generate_with_backoff(items)
                for t,r in zip(chunk,results):
                    st.after_segment(t,r)
                texts = [tok.apply_chat_template(prep(t.messages),tools=None,add_generation_prompt=True,tokenize=False) for t in chunk]
                lens = [len(x) for x in tok(texts,add_special_tokens=False)['input_ids']]
                for t,lb in zip(chunk,lens):
                    st.finalize_segment(t,lb)
                schedule['cursor'] += len(chunk)
                schedule['choices'] += len(chunk)
                schedule['block_choices'] += len(chunk)
                now=time.monotonic()
                schedule['stage_seconds'][block] += now-stage_tick
                stage_tick=now
                store.save(chunk,schedule)
                rt.report_progress(schedule['choices'],49200,output)
            store.export()
            if stopped:
                break
            schedule['pending_order'] = [i for i in schedule['order'] if not trials[i].done]
            schedule['order']=[];schedule['cursor']=0
            store.save([],schedule)
            gc.collect();torch.cuda.empty_cache()
        now=time.monotonic()
        schedule['stage_seconds'][block] += now-stage_tick
        rt.atomic_json(output/(block+'_completion.json'),{'status':'resumable' if stopped else 'completed',
            'completed_trials':sum(t.done for t in trials if t.record['block']==block),
            'completed_choices':sum(len(t.record['choices']) for t in trials if t.record['block']==block),
            'exclusive_seconds':schedule['stage_seconds'][block]})
        rt.emit(output,'stage_end',stage=block,status='resumable' if stopped else 'completed',seconds=schedule['stage_seconds'][block])
        if stopped:
            store.save([],schedule)
            break
        schedule.update(block_index=block_index+1,round=0,order=[],cursor=0,block_choices=0,pending_order=[])
        store.save([],schedule)
    store.export()
    rt.atomic_json(output/'completion.json',{'status':'resumable' if stopped else 'completed',
        'requested_trials':5330,'completed_trials':sum(t.done for t in trials),'completed_choices':schedule['choices'],
        'shared_setup_seconds_this_attempt':shared_setup,'stage_seconds':schedule['stage_seconds'],
        'gpu_count':1,'allocation_seconds':None,'allocation_timing_status':'provider receipt required',
        'config':config})
    h1.remove();h2.remove()
    return not stopped
